# Generated by Django 6.0.2 on 2026-02-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('arcana_type', models.CharField(choices=[('Ст. Аркан', 'Старший Аркан'), ('Мл. Аркан', 'Младший Аркан')], default='Мл. Аркан', max_length=20, verbose_name='Тип аркана')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер карты')),
                ('description', models.TextField(verbose_name='Прямое значение')),
                ('description_flip', models.TextField(blank=True, verbose_name='Перевёрнутое значение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tarot/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Карта Таро',
                'verbose_name_plural': 'Карты Таро',
                'ordering': ['number', 'name'],
            },
        ),
    ]
