# Generated by Django 6.0.2 on 2026-03-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_data', models.JSONField(default=dict, verbose_name='Данные Human Design')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Human Design',
                'verbose_name_plural': 'Human Designs',
            },
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Руна',
                'verbose_name_plural': 'Руны',
            },
        ),
    ]
