# Generated by Django 6.0.2 on 2026-03-03 17:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tarot_app', '0002_humandesign_rune'),
        ('tg_bot', '0001_drop_old_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Длительность (дни)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Вид подписки',
                'verbose_name_plural': 'Виды подписок',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('birth_time', models.TimeField(blank=True, null=True, verbose_name='Время рождения')),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email подтверждён')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Часовой пояс')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='tg_bot_user_set', related_query_name='tg_bot_user', to='auth.group', verbose_name='groups')),
                ('saved_human_design', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='tarot_app.humandesign', verbose_name='Сохранённый Human Design')),
                ('saved_runes', models.ManyToManyField(blank=True, related_name='saved_by_users', to='tarot_app.rune', verbose_name='Сохранённые руны')),
                ('saved_tarot_spreads', models.ManyToManyField(blank=True, related_name='saved_by_users', to='tarot_app.tarotcard', verbose_name='Сохранённые расклады Таро')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='tg_bot_user_set', related_query_name='tg_bot_user', to='auth.permission', verbose_name='user permissions')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tg_bot.subscription', verbose_name='Текущая подписка')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
