# Generated by Django 6.0.2 on 2026-03-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_initial'),
    ]

    operations = [
    ]
